spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forum
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: ff388ae34e9e48
    password: 199bc33c08ee2b
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: secreto