spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:forum;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
jwt:
  secret: secreto